backend: 'torch'
verbose: 1


seed: 123

use_gpu: True

split:
  tau: 47.22089357334237  # rec
  eta: 0.05702557067627598 #  reg
  alpha: 0.17012548528024396 # mix

data:
  type: movie
  unaligned_rate: 1.0 
  splits: [1.0, 0.0, 0.0]
  correspondence: False   
  root: data/
  cluster_num: 1    
  num_views: 1
  modality_feature_names: []
  modality_feature_dims: []     

model:
  h_dim: 367
  z_dim: 333

mixer:
  inner_iter: 5
  loss_fn: L2 # KL
  gw_method: 'fgw'  # 'w'
  consist: False  # consist fgw or not
  f_alpha: 0.095333

train:
  batch_or_epoch: epoch
  local_update_steps: 120    # epoch
  
  batch_size: 400

  optimizer:
    type: Adam
    lr: 0.02523676240972713  #  lr
    weight_decay: 0.0

  scheduler:
    type: ReduceLROnPlateau
    mode: 'max'
    factor: 0.95
    patience: 10
    threshold: 1e-7
    min_lr: 1e-8

nni: True

device: 1 

baseline: mwae_b0


outdir:
  save_to: mwae
  restore_from: mwae
  dir: mwae
  expname: movie
  expname_tag: unalign